version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    labels:
      - dependencies
      - actions
      - Skip Changelog
    schedule:
      interval: weekly
      day: sunday
  - package-ecosystem: pip
    directory: /
    labels:
      - dependencies
      - python
      - Skip Changelog
    schedule:
      interval: weekly
      day: sunday