label: clingy flow
description: sample description
steps:
- label: start
  description: starting clingy flow
  command: echo 
  args:
    - "Starting"
- label: run the help command
  command: ./nn.pex
- label: run the all command
  command: ./nn.pex all
- label: run the page 2 of all command
  command: ./nn.pex all -p 2
